chore: rename files

diff --git a/bin/sync_dotfiles b/bin/sync_dotfiles
--- a/bin/sync_dotfiles
+++ b/bin/sync_dotfiles
@@ -18,13 +18,13 @@ cd_or_error "$DOTFILES_DIR"
 
 stow_dotfiles() {
     info "Stowing dotfiles from: $DOTFILES_DIR"
-    [ -d "stow" ] || error "'stow' directory not found."
+    [ -d "config" ] || error "'stow' directory not found."
 
-    for pkg in stow/*; do
+    for pkg in config/*; do
         [ -d "$pkg" ] || continue
         pkg_name=$(basename "$pkg")
         info "Stowing package: $pkg_name"
-        stow -d stow -t "$HOME" --restow "$pkg_name"
+        stow -d config -t "$HOME" --restow "$pkg_name"
     done
 
     if [ -d "private" ]; then
